#!/bin/bash
#install.sh executes the makefile at the beggining. It then creates the necessary folders and copies the exicutable files in them generated by the makefile and gives
#them the proper permissions. It creates two fifo's request_fifo and response_fifo for communication with the database server and starts the database server.
#finally it runs the perl script list_users_and_groups.pl.

export USE_RWFM=0
export hexNum=`hostid`
export HOSTID=`printf "%d" 0x${hexNum}`
export HOSTNAME=`hostname`
export ADD_USER=0
export ADD_GROUP=1

#Deleting old files generated
./clean.sh
./create_macro_file.sh

make || {
        echo "failed to build preload library."
        exit 1
}
echo "library built"

mkdir -p /lib/secos/
cp -f preload.so /lib/secos/
echo "library copied"

mkdir -p /opt/secos/bin/
cp -f database_server secure_shell enable_rwfm /opt/secos/bin/
chmod +x /opt/secos/bin/*

touch /tmp/msg_queue_file

chmod 777 /tmp/msg_queue_file

/opt/secos/bin/database_server &
echo "database server started"

perl -w list_users_and_groups.pl ${HOSTNAME}

exit 0
